### ISSUE TITLE
API KEY AUTH disabled and enabled in deferent controllers

### ISSUE THREAD

**Issue by abdallahmaali** [Hanisch-IT/codeigniter-restserver#1]
i want to disable  auth  in public section   and enabled it in private section  like user  profile 
but i don't know how i could do this

**Comment by Hanisch-IT** [comment]
Pleasy ask questions to the official page.:

https://github.com/chriskacerguis/codeigniter-restserver

I will update my fork as fast as i can with every update on the main project.
